apiVersion: kaptain.org/1.29
kind: basic-quality-and-versioning
metadata:
  description: "AWS EKS cluster management layerset - composes quality and build configuration"

spec:
  layers:
    - layer-github-flow-strict:[1.4,2.0)
    - layer-aws-eks-cluster-management:[1.11,2.0)
